<?php

// config for Abdiwaahid/LanguageSwitcher
return [

    // 'session' or 'cache'
    'driver' => 'session',

    // The guard to use for authenticated users.
    // If null, will use the default guard.
    'guard' => null,

    // The key used in the storage driver.
    'key' => 'locale_',

    'languages' => [
        'al' => 'Albanian',
        'ar' => 'Arabic',
        'be' => 'Belarusian',
        'bs' => 'Bosnian',
        'cn' => 'Chinese',
        'ee' => 'Estonian',
        'gb' => 'British English',
        'hu' => 'Hungarian',
        'ir' => 'Iranian',
        'lv' => 'Latvian',
        'nl' => 'Dutch',
        'pt' => 'Portuguese',
        'se' => 'Swedish',
        'tr' => 'Turkish',
        'vn' => 'Vietnamese',
        'am' => 'Armenian',
        'bg' => 'Bulgarian',
        'cs' => 'Czech',
        'es' => 'Spanish',
        'ge' => 'Georgian',
        'id' => 'Indonesian',
        'it' => 'Italian',
        'mk' => 'Macedonian',
        'no' => 'Norwegian',
        'ro' => 'Romanian',
        'sg' => 'Singaporean',
        'tw' => 'Taiwanese',
        'at' => 'Austrian',
        'br' => 'Brazilian',
        'cz' => 'Czech',
        'eu' => 'European',
        'gr' => 'Greek',
        'ie' => 'Irish',
        'jp' => 'Japanese',
        'mx' => 'Mexican',
        'np' => 'Nepalese',
        'rs' => 'Serbian',
        'sk' => 'Slovakian',
        'ua' => 'Ukrainian',
        'au' => 'Australian',
        'ca' => 'Canadian',
        'de' => 'German',
        'fi' => 'Finnish',
        'hk' => 'Hong Kong',
        'il' => 'Israeli',
        'kr' => 'Korean',
        'my' => 'Malaysian',
        'pk' => 'Pakistani',
        'ru' => 'Russian',
        'sl' => 'Slovenian',
        'so' => 'Somali',
        'us' => 'American',
        'bd' => 'Bangladeshi',
        'ch' => 'Chinese',
        'dk' => 'Danish',
        'fr' => 'French',
        'hr' => 'Croatian',
        'in' => 'Indian',
        'lt' => 'Lithuanian',
        'ng' => 'Nigerian',
        'pl' => 'Polish',
        'sa' => 'Saudi',
        'th' => 'Thai',
        'uz' => 'Uzbek',
    ],
];
